
package ws_package;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "userServices", targetNamespace = "http://kz.sdu.edu.j2ee.app.project.ws", wsdlLocation = "http://127.0.0.1:8080/project_ws/user?wsdl")
public class UserServices
    extends Service
{

    private final static URL USERSERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ws_package.UserServices.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ws_package.UserServices.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/project_ws/user?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/project_ws/user?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        USERSERVICES_WSDL_LOCATION = url;
    }

    public UserServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServices() {
        super(USERSERVICES_WSDL_LOCATION, new QName("http://kz.sdu.edu.j2ee.app.project.ws", "userServices"));
    }

    /**
     * 
     * @return
     *     returns UserServicesWS
     */
    @WebEndpoint(name = "UserServicesWSPort")
    public UserServicesWS getUserServicesWSPort() {
        return super.getPort(new QName("http://kz.sdu.edu.j2ee.app.project.ws", "UserServicesWSPort"), UserServicesWS.class);
    }

}
