
package ws_package;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "UserServicesWS", targetNamespace = "http://kz.sdu.edu.j2ee.app.project.ws")
public interface UserServicesWS {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://kz.sdu.edu.j2ee.app.project.ws", className = "ws_package.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://kz.sdu.edu.j2ee.app.project.ws", className = "ws_package.InitResponse")
    public void init();

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "remove", targetNamespace = "http://kz.sdu.edu.j2ee.app.project.ws", className = "ws_package.Remove")
    @ResponseWrapper(localName = "removeResponse", targetNamespace = "http://kz.sdu.edu.j2ee.app.project.ws", className = "ws_package.RemoveResponse")
    public void remove();

}
